version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT

      - run:
          name: Add SSH Key to Known Hosts
          command: echo "[server_ip]:[port] [host_key]" >> ~/.ssh/known_hosts

      - run:
          name: Deploy Go Application
          command: |
            scp -P $SSH_PORT deploy.sh $USER@$SERVER_IP:/tmp/deploy.sh
            ssh -p $SSH_PORT $USER@$SERVER_IP bash /tmp/deploy.sh $APP_NAME $DOMAIN $EMAIL

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
                - master
