version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"

      - run:
          name: Deploy Go Application
          command: |
            scp deploy.sh $USER@$SERVER_IP:/tmp/deploy.sh
            ssh $USER@$SERVER_IP bash /tmp/deploy.sh $APP_NAME $DOMAIN $EMAIL

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
                - master
